// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDB6Q1kOSKzYC8xxBVl2rvtviwoqrpwt2Y',
    appId: '1:740954650941:web:f463505bcf771b6f8bad54',
    messagingSenderId: '740954650941',
    projectId: 'garrison-87625',
    authDomain: 'garrison-87625.firebaseapp.com',
    storageBucket: 'garrison-87625.firebasestorage.app',
    measurementId: 'G-LWH38N9QPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtJDf_RWahdUlkaIMBtK--CqGQG7gyKzI',
    appId: '1:740954650941:android:8dcc34779ae5c8938bad54',
    messagingSenderId: '740954650941',
    projectId: 'garrison-87625',
    storageBucket: 'garrison-87625.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYdPYYAVQjFK5Oyttu9-Vxp2aQv5aZRt4',
    appId: '1:740954650941:ios:bc9b6b95807abe488bad54',
    messagingSenderId: '740954650941',
    projectId: 'garrison-87625',
    storageBucket: 'garrison-87625.firebasestorage.app',
    iosBundleId: 'com.hummingbird.garrison',
  );
}
